// AUTO-GENERATED by scripts/cld-upload.mjs — do not edit by hand.
// Each export is a Cloudinary publicId. Use with <CldImage publicId={...} /> or cldUrl(...).

export const beautyAsset = { publicId: "websites/sm-luxe-salon/services/beauty", w: 2400, h: 1600, kind: "image" as const };
export const beauty = "websites/sm-luxe-salon/services/beauty";
export const beauty1Asset = { publicId: "websites/sm-luxe-salon/services/beauty1", w: 2400, h: 1599, kind: "image" as const };
export const beauty1 = "websites/sm-luxe-salon/services/beauty1";
export const familyImageAsset = { publicId: "websites/sm-luxe-salon/services/familyimage", w: 2400, h: 3600, kind: "image" as const };
export const familyImage = "websites/sm-luxe-salon/services/familyimage";
export const hairServiceAsset = { publicId: "websites/sm-luxe-salon/services/hairservice", w: 1360, h: 907, kind: "image" as const };
export const hairService = "websites/sm-luxe-salon/services/hairservice";
export const nailAsset = { publicId: "websites/sm-luxe-salon/services/nail", w: 1600, h: 1200, kind: "image" as const };
export const nail = "websites/sm-luxe-salon/services/nail";
export const reviewImageAsset = { publicId: "websites/sm-luxe-salon/services/reviewimage", w: 2400, h: 1600, kind: "image" as const };
export const reviewImage = "websites/sm-luxe-salon/services/reviewimage";
export const makeupAsset = { publicId: "websites/sm-luxe-salon/services/makeup", w: 2400, h: 2400, kind: "image" as const };
export const makeup = "websites/sm-luxe-salon/services/makeup";
