// AUTO-GENERATED by scripts/cld-upload.mjs — do not edit by hand.
// Each export is a Cloudinary publicId. Use with <CldImage publicId={...} /> or cldUrl(...).

export const dashaFacialAsset = { publicId: "websites/sm-luxe-salon/videos/dashafacial", w: 480, h: 848, kind: "video" as const };
export const dashaFacial = "websites/sm-luxe-salon/videos/dashafacial";
export const highMakeupTrimmedAsset = { publicId: "websites/sm-luxe-salon/videos/highmakeuptrimmed", w: 1920, h: 1080, kind: "video" as const };
export const highMakeupTrimmed = "websites/sm-luxe-salon/videos/highmakeuptrimmed";
