// AUTO-GENERATED by scripts/cld-upload.mjs — do not edit by hand.
// Each export is a Cloudinary publicId. Use with <CldImage publicId={...} /> or cldUrl(...).

export const aparnaHighFashionAsset = { publicId: "websites/sm-luxe-salon/about/aparnahighfashion", w: 1350, h: 2400, kind: "image" as const };
export const aparnaHighFashion = "websites/sm-luxe-salon/about/aparnahighfashion";
export const jabiliPartyAsset = { publicId: "websites/sm-luxe-salon/about/jabiliparty", w: 1350, h: 2400, kind: "image" as const };
export const jabiliParty = "websites/sm-luxe-salon/about/jabiliparty";
export const lashCertificateAsset = { publicId: "websites/sm-luxe-salon/about/lashcertificate", w: 946, h: 2048, kind: "image" as const };
export const lashCertificate = "websites/sm-luxe-salon/about/lashcertificate";
export const modelpartyAsset = { publicId: "websites/sm-luxe-salon/about/modelparty", w: 2400, h: 1599, kind: "image" as const };
export const modelparty = "websites/sm-luxe-salon/about/modelparty";
