// AUTO-GENERATED by scripts/cld-upload.mjs — do not edit by hand.
// Each export is a Cloudinary publicId. Use with <CldImage publicId={...} /> or cldUrl(...).

export const nailandPedicureViewAsset = { publicId: "websites/sm-luxe-salon/desktop/nailandpedicureview", w: 2400, h: 1600, kind: "image" as const };
export const nailandPedicureView = "websites/sm-luxe-salon/desktop/nailandpedicureview";
export const s1Asset = { publicId: "websites/sm-luxe-salon/desktop/s1", w: 1800, h: 1200, kind: "image" as const };
export const s1 = "websites/sm-luxe-salon/desktop/s1";
export const s2Asset = { publicId: "websites/sm-luxe-salon/desktop/s2", w: 1800, h: 1200, kind: "image" as const };
export const s2 = "websites/sm-luxe-salon/desktop/s2";
export const s3Asset = { publicId: "websites/sm-luxe-salon/desktop/s3", w: 1757, h: 1040, kind: "image" as const };
export const s3 = "websites/sm-luxe-salon/desktop/s3";
export const s4Asset = { publicId: "websites/sm-luxe-salon/desktop/s4", w: 2400, h: 1600, kind: "image" as const };
export const s4 = "websites/sm-luxe-salon/desktop/s4";
export const s5Asset = { publicId: "websites/sm-luxe-salon/desktop/s5", w: 2400, h: 1599, kind: "image" as const };
export const s5 = "websites/sm-luxe-salon/desktop/s5";
export const s6Asset = { publicId: "websites/sm-luxe-salon/desktop/s6", w: 2400, h: 1599, kind: "image" as const };
export const s6 = "websites/sm-luxe-salon/desktop/s6";
export const s7Asset = { publicId: "websites/sm-luxe-salon/desktop/s7", w: 2400, h: 1598, kind: "image" as const };
export const s7 = "websites/sm-luxe-salon/desktop/s7";
