// AUTO-GENERATED by scripts/cld-upload.mjs — do not edit by hand.
// Each export is a Cloudinary publicId. Use with <CldImage publicId={...} /> or cldUrl(...).

export const divMakeupContactAsset = { publicId: "websites/sm-luxe-salon/mobile/divmakeupcontact", w: 1600, h: 2400, kind: "image" as const };
export const divMakeupContact = "websites/sm-luxe-salon/mobile/divmakeupcontact";
export const inaraHairColorAsset = { publicId: "websites/sm-luxe-salon/mobile/inarahaircolor", w: 1200, h: 1600, kind: "image" as const };
export const inaraHairColor = "websites/sm-luxe-salon/mobile/inarahaircolor";
export const m1Asset = { publicId: "websites/sm-luxe-salon/mobile/m1", w: 1616, h: 2400, kind: "image" as const };
export const m1 = "websites/sm-luxe-salon/mobile/m1";
export const m2Asset = { publicId: "websites/sm-luxe-salon/mobile/m2", w: 1350, h: 2400, kind: "image" as const };
export const m2 = "websites/sm-luxe-salon/mobile/m2";
export const m3Asset = { publicId: "websites/sm-luxe-salon/mobile/m3", w: 3024, h: 4032, kind: "image" as const };
export const m3 = "websites/sm-luxe-salon/mobile/m3";
export const m4Asset = { publicId: "websites/sm-luxe-salon/mobile/m4", w: 1800, h: 2400, kind: "image" as const };
export const m4 = "websites/sm-luxe-salon/mobile/m4";
export const m5Asset = { publicId: "websites/sm-luxe-salon/mobile/m5", w: 3024, h: 4032, kind: "image" as const };
export const m5 = "websites/sm-luxe-salon/mobile/m5";
export const m6Asset = { publicId: "websites/sm-luxe-salon/mobile/m6", w: 3024, h: 4032, kind: "image" as const };
export const m6 = "websites/sm-luxe-salon/mobile/m6";
