/**
 * AUTO-GENERATED by scripts/fetch-google-rating.mjs — do not edit by hand.
 *
 * Live Google rating + review count for the salon, refreshed at build time from
 * the Google Places API. The committed values below are the FALLBACK used when
 * the build-time fetch is unavailable (no API key, network/API error, or a plain
 * local build) so the rating badge + AggregateRating schema never break.
 *
 * GoogleRatingBadge.tsx reads these constants for BOTH the visible badge and the
 * JSON-LD, so the number a human sees and the number Google reads can never drift.
 *
 * Refresh manually with: `npm run fetch:rating` (needs GOOGLE_PLACES_API_KEY).
 */
export const GOOGLE_RATING = 4.9;
export const GOOGLE_REVIEW_COUNT = 471;
export const GOOGLE_RATING_FETCHED_AT = "2026-06-09";
